version: "3"
services:
  # Spring Boot Application
  spring-boot-app:
    image: back
    build: ./PdsBackend
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/Gesti
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root 
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql  

  # MySQL Database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Gesti'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '0.0.0.0:3306:3306' 
    volumes:
      - demo:/var/lib/mysql  

  front:
    image: front
    build: ./PdsFront
    restart: always
    ports:
      - "0.0.0.0:4200:4200"


volumes:
  demo:
