version: "3"
services:
  # Spring Boot Application
  back:
    image: dalibm98/back:latest
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/Gesti
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root 
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql  

  # MySQL Database
  mysql:
    image: dalibm98/mysql-gesti:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'Gesti'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '0.0.0.0:3306:3306' 
    volumes:
      - Gesti:/var/lib/mysql  

  front:
    image: dalibm98/front:latest
    ports:
      - "0.0.0.0:4200:80"

volumes:
  Gesti:

